org: app
app: serverless-adonis
service: adonisv5

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    NODE_ENV: development
    PORT: 3333
    HOST: localhost
    APP_KEY: TVTj8OCKxhHhHWeyZHkVhK1TPL7ghIK9

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  index:
    handler: lambda.handle
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{handle+}'
          method: any